project:
  type: website
  output-dir: docs

website:
  title: "Neighbourhood Transport Environment Typology"
  navbar:
    right:
      - icon: github
        href: https://github.com/scc-pi/transport-env-typology
        aria-label: GitHub

format:
  html:
    theme: cosmo

execute:
  freeze: auto